#pragma once

//  FN call command defines
#define PM_CLOSESRC				WM_APP + 0x0001
#define PM_OPENSRC				WM_APP + 0x0002
#define PM_FINISH				WM_APP + 0x0003
#define PM_INIT					WM_APP + 0x0004
#define PM_GETDEFAULTSOURCE		WM_APP + 0x0005
#define PM_SELECTSRC			WM_APP + 0x0006
#define PM_ENUMSRCS				WM_APP + 0x0007
#define PM_SETSELECTEDSOURCE	WM_APP + 0x0008
#define PM_SETPIXELTYPE			WM_APP + 0x0009
#define PM_ENUMPIXELTYPES		WM_APP + 0x000A
#define PM_SETBITDEPTH			WM_APP + 0x000B
#define PM_ENUMBITDEPTHS		WM_APP + 0x000C
#define PM_SETRESOLUTION		WM_APP + 0x000D
#define PM_GETRESOLUTIONRANGE	WM_APP + 0x000E
#define PM_ENUMRESOLUTIONS		WM_APP + 0x000F
#define PM_ACQUIRE				WM_APP + 0x0010
#define PM_TRANSFERPICTURES		WM_APP + 0x0011
#define PM_RELEASE				WM_APP + 0x0012
#define PM_SHOWUI				WM_APP + 0x0013
#define PM_ENUMCAPS				WM_APP + 0x0014
#define PM_ENUMPAGESIZES		WM_APP + 0x0015
#define PM_SETPAGESIZE			WM_APP + 0x0016
#define PM_SETFEEDERENABLED		WM_APP + 0x0017
#define PM_SETDUPLEX			WM_APP + 0x0018



#define PM_PING					WM_APP + 0x0100
#define PM_PICSTART				WM_APP + 0x0200
#define PM_PICDATA				WM_APP + 0x0201
#define PM_PICDONE				WM_APP + 0x0202
#define PM_TRANSFERDONE			WM_APP + 0x0203
#define PM_TRANSFERREADY		WM_APP + 0x0204
#define PM_FNCOMPLETE			WM_APP + 0x0205

#define PM_ACQUIREDIRECT			WM_APP + 0x0206
#define PM_TRANSFERDIRECTPICTURES	WM_APP + 0x0207
#define PM_TRANSFERDIRECTREADY		WM_APP + 0x0208
#define PM_TRANSFERDIRECTDONE		WM_APP + 0x0209

#define PM_ACKPICDATA			WM_APP + 0x020A

#define PM_VERCHECK				WM_APP + 0x0300

#define PM_LOCALLAUNCH			WM_APP + 0x0401
#define PM_SETPREFERENCES       WM_APP + 0x0402 

#define GETDEFAULTSRCEVENT		0
#define ENUMSRCSEVENT			1
#define ENUMPIXELTYPESEVENT		2
#define ENUMBITDEPTHSEVENT		3
#define	GETRESOLUTIONRANGEEVENT 4
#define	ENUMRESOLUTIONSEVENT	5
#define	TRANSFERPICTURESEVENT	6
#define TRANSFERREADYEVENT		7
#define FNCOMPLETEEVENT			8
#define TRANSFERDIRECTDONEEVENT 9
#define ENUMCAPSEVENT			10
#define ENUMPAGESIZESEVENT		11
#define VERCHECKEVENT			12

#define NUM_EVENTS 13

extern HANDLE hWaits[NUM_EVENTS];

#define SCAN_VERSION			4

LPWSTR TranslateCommand(int nCmd);
void DataArrival(LPBYTE pBuf, USHORT usLength);
LPBYTE Poll();

void DataArrivalServerCommand(LPBYTE pBuf, USHORT usLength);
